[project]
name = "chartout"
version = "0.1.0"
description = "Print Your Insights, Anytime, Anywhere"
channels = ["conda-forge", "nodefaults"]
platforms = ["osx-arm64", "osx-64", "linux-64", "linux-aarch64", "win-64"]

[tasks]
# Development tasks
lab = "jupyter-lab --notebook-dir=python"
test = { cmd = "pytest", cwd = "python" }

[pypi-dependencies]
chartout = { path = "./python", editable = true }

[dependencies]
python = ">=3.9"
jupyterlab = "*"
altair = "*"
vl-convert-python = ">=1.7"
vega_datasets = "*"
anywidget = "*"
numpy = "*"
pillow = "*"
pandas = "*"
pytest = "*"

